[package]
name = "rev_store_import"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12.15", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
tokio = {version = "1.38.0", features=["full"]}