--TEMP_INV
SELECT
    INV.ID,
    INV.NAME,
    DIV.NAME AS DIVISION_NAME,
    CONCAT('gst',CAST(GST_TAX.TAXPER AS INT)) as GST_TAX,
    (CASE WHEN INV.BRANDID=0 THEN ''
        WHEN INV.BRANDID>0 THEN BRAND_CO.NAME END) AS CATEGORY1,
    (CASE WHEN INV.CATID=0 THEN ''
        WHEN INV.CATID>0 THEN CATEGORY_CO.NAME END) AS CATEGORY2,
    (CASE WHEN INV.SCATID=0 THEN ''
        WHEN INV.SCATID>0 THEN SUBCATEGORY_CO.NAME END) AS CATEGORY3,
    (CASE WHEN INV.SSCATID=0 THEN ''
        WHEN INV.SSCATID>0 THEN SPLSUBCATEGORY_CO.NAME END) AS CATEGORY4,
    INV.TAGNO AS BARCODE,
    INV.HSNCODE AS HSN_CODE,
    INV.PRODUCTMRP AS MRP,
    INV.SELRATE AS S_RATE,
    (CASE WHEN PU_BILLTYPEID='B' THEN 'TYPE_B' --ALL READONLY
        WHEN PU_BILLTYPEID='C' THEN 'TYPE_C' --DISC2 EDITABLE, OTHER ALL READONLY
    END) AS PUR_BILL_TYPE,
    (CASE WHEN INV.WSALEDISPER>0.0 THEN INV.WSALEDISPER END) AS PRICE_CONFIG_DISC1,
    (CASE WHEN INV.RETAILDISPER>0.0 THEN INV.RETAILDISPER END) AS PRICE_CONFIG_DISC2,
    INV.INCLUDETAX AS TAX_INCL,
    (CASE WHEN INV.COSTRATE>0.0 THEN INV.COSTRATE END) AS COSTRATE,
    (CASE WHEN INV.PRATE>0.0 THEN INV.PRATE END) AS PRATE,
    (CASE WHEN INV.MARKUPPER>0.0 THEN INV.MARKUPPER END) AS PC_COST_MRP_MARKDOWN,
    (CASE WHEN INV.MARKDOWNPER>0.0 THEN INV.MARKDOWNPER END) AS PC_COST_MRP_DISCOUNT,
    (CASE WHEN INV.PMARGIN>0.0 THEN INV.PMARGIN END) AS PC_SRATE_LANDCOST_MARKUP,
    (CASE WHEN INV.MRPMARGINPER>0.0 THEN INV.MRPMARGINPER END) AS PC_SRATE_MRP_DISCOUNT
FROM ARM_PRODUCT AS INV
    LEFT JOIN ARM_ITEMCOUNTER AS DIV ON INV.ITEMCOUNTER=DIV.ID
    LEFT JOIN GBM_MISCMASTER AS BRAND_CO ON INV.BRANDID=BRAND_CO.ID
    LEFT JOIN GBM_MISCMASTER AS CATEGORY_CO ON INV.CATID=CATEGORY_CO.ID
    LEFT JOIN GBM_MISCMASTER AS SUBCATEGORY_CO ON INV.SCATID=SUBCATEGORY_CO.ID
    LEFT JOIN GBM_MISCMASTER AS SPLSUBCATEGORY_CO ON INV.SSCATID=SPLSUBCATEGORY_CO.ID
    LEFT JOIN ARM_TAXMASTER AS GST_TAX ON INV.TAX=GST_TAX.ID
-- WHERE INV.PU_BILLTYPEID='B'
-- WHERE INV.PU_BILLTYPEID='C'
-- WHERE INV.PU_BILLTYPEID NOT IN ('B','C')
ORDER BY ID
OFFSET 0 ROWS
FETCH NEXT 1000 ROWS ONLY;

-- read all inventory with all column from rsradmindb.ARM_PRODUCT
SELECT
    INV.PRODCODE AS ID,
    INV.NAME,
    INV.TAGNO AS BARCODE,
    INV.TAGNAME AS DISPLAY_NAME,
    CAST(INV.ITEMCOUNTER AS INT) AS DIVISION_ID,
    DIV.NAME AS DIVISION_NAME,
    INV.BRANDID,
    (CASE WHEN INV.BRANDID=0 THEN ''
        WHEN INV.BRANDID>0 THEN BRAND_CO.NAME END) AS BRAND_NAME,
    INV.CATID AS CATEGORY_ID,
    (CASE WHEN INV.CATID=0 THEN ''
        WHEN INV.CATID>0 THEN CATEGORY_CO.NAME END) AS CATEGORY_NAME,
    INV.SCATID AS SUBCATEGORY_ID,
    (CASE WHEN INV.SCATID=0 THEN ''
        WHEN INV.SCATID>0 THEN SUBCATEGORY_CO.NAME END) AS SUBCATEGORY_NAME,
    INV.SSCATID AS SPLSUBCATEGORY_ID,
    (CASE WHEN INV.SSCATID=0 THEN ''
        WHEN INV.SSCATID>0 THEN SPLSUBCATEGORY_CO.NAME END) AS SPLSUBCATEGORY_NAME,
    'PCS' AS UNIT_NAME,
    SELRATE AS SALE_RATE,
    INV.PRODUCTMRP AS PRICE_CONFIG_MRP,
    INV.WSALEDISPER AS PRICE_CONFIG_DISC1,
    INV.RETAILDISPER AS PRICE_CONFIG_DISC2,
    GST_TAX.TAXNAME AS TAX_NAME,
    GST_TAX.TAXPER AS TAX_RATIO,
    INV.INCLUDETAX AS TAX_INCL,
    INV.COSTRATE,
    INV.PRATE,
    INV.HSNCODE,
    INV.INCENTIVE,
    INV.ONLSALE AS ONLINE_SALE,
    (CASE WHEN INV.MARKUPPER>0.0 THEN INV.MARKUPPER END) AS PC_COST_MRP_MARKDOWN,
    (CASE WHEN INV.MARKDOWNPER>0.0 THEN INV.MARKDOWNPER END) AS PC_COST_MRP_DISCOUNT,
    (CASE WHEN INV.PMARGIN>0.0 THEN INV.PMARGIN END) AS PC_SRATE_LANDCOST_MARKUP,
    (CASE WHEN INV.MRPMARGINPER>0.0 THEN INV.MRPMARGINPER END) AS PC_SRATE_MRP_DISCOUNT,
    INV.MINSTOCK,
    INV.MAXSTOCK,
    INV.CURRSTOCK,
    INV.REORDERSTOCK,
    (CASE WHEN PU_BILLTYPEID='A' THEN 'TYPE_A' --ALL EDITABLE
        WHEN PU_BILLTYPEID='B' THEN 'TYPE_B' --ALL READONLY
        WHEN PU_BILLTYPEID='C' THEN 'TYPE_C' --DISC2 EDITABLE, OTHER ALL READONLY
--         WHEN PU_BILLTYPEID='W' THEN 'WEIGHT' -- ALL EDITABLE
--         WHEN PU_BILLTYPEID='T' THEN 'METER' --  ALL EDITABLE
        ELSE 'OTHERS' --ALL EDITABLE
        END) AS PUR_BILL_TYPE
FROM ARM_PRODUCT AS INV
    LEFT JOIN ARM_ITEMCOUNTER AS DIV ON INV.ITEMCOUNTER=DIV.ID
    LEFT JOIN GBM_MISCMASTER AS BRAND_CO ON INV.BRANDID=BRAND_CO.ID
    LEFT JOIN GBM_MISCMASTER AS CATEGORY_CO ON INV.CATID=CATEGORY_CO.ID
    LEFT JOIN GBM_MISCMASTER AS SUBCATEGORY_CO ON INV.SCATID=SUBCATEGORY_CO.ID
    LEFT JOIN GBM_MISCMASTER AS SPLSUBCATEGORY_CO ON INV.SSCATID=SPLSUBCATEGORY_CO.ID
    LEFT JOIN ARM_TAXMASTER AS GST_TAX ON INV.TAX=GST_TAX.ID

ORDER BY INV.PRODCODE
OFFSET 0 ROWS
FETCH NEXT 1000 ROWS ONLY;

